# Generated by Django 5.2.7 on 2025-10-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Registro"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Fabricante"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Capacidad de Pasajeros"),
                ),
                (
                    "year_manufactured",
                    models.PositiveIntegerField(verbose_name="Año de Fabricación"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operacional"),
                            ("MAINTENANCE", "Mantenimiento"),
                            ("OUT_OF_SERVICE", "Fuera de Servicio"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Última Fecha de Mantenimiento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aeronave",
                "verbose_name_plural": "Aeronaves",
                "ordering": ["registration_number"],
            },
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "gate_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código de Puerta"
                    ),
                ),
                ("terminal", models.CharField(max_length=50, verbose_name="Terminal")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Puerta de Embarque",
                "verbose_name_plural": "Puertas de Embarque",
                "ordering": ["gate_code"],
            },
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="ID de Empleado"
                    ),
                ),
                (
                    "personnel_type",
                    models.CharField(
                        choices=[("PILOT", "Piloto"), ("COPILOT", "Copiloto")],
                        max_length=10,
                        verbose_name="Tipo de Personal",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Licencia"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(verbose_name="Años de Experiencia"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal",
                "verbose_name_plural": "Personal",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ResourceConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("CO_REQUISITE", "Co-requisito"),
                            ("MUTUAL_EXCLUSION", "Exclusión Mutua"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Restricción",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Restricción de Recursos",
                "verbose_name_plural": "Restricciones de Recursos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Runway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "runway_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Código de Pista"
                    ),
                ),
                (
                    "length_meters",
                    models.PositiveIntegerField(verbose_name="Longitud (metros)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pista",
                "verbose_name_plural": "Pistas",
                "ordering": ["runway_code"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Vuelo"
                    ),
                ),
                ("origin", models.CharField(max_length=100, verbose_name="Origen")),
                (
                    "destination",
                    models.CharField(max_length=100, verbose_name="Destino"),
                ),
                ("departure_time", models.DateTimeField(verbose_name="Hora de Salida")),
                ("arrival_time", models.DateTimeField(verbose_name="Hora de Llegada")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("IN_PROGRESS", "En Progreso"),
                            ("COMPLETED", "Completado"),
                            ("CANCELLED", "Cancelado"),
                            ("DELAYED", "Retrasado"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="airline_app.aircraft",
                        verbose_name="Aeronave",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="airline_app.gate",
                        verbose_name="Puerta",
                    ),
                ),
                (
                    "copilots",
                    models.ManyToManyField(
                        limit_choices_to={
                            "is_active": True,
                            "personnel_type": "COPILOT",
                        },
                        related_name="flights_as_copilot",
                        to="airline_app.personnel",
                        verbose_name="Copilotos",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "personnel_type": "PILOT"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights_as_pilot",
                        to="airline_app.personnel",
                        verbose_name="Piloto",
                    ),
                ),
                (
                    "runway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="airline_app.runway",
                        verbose_name="Pista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vuelo",
                "verbose_name_plural": "Vuelos",
                "ordering": ["-departure_time"],
            },
        ),
    ]
