# Generated by Django 5.2.7 on 2025-10-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourceConstraint",
        ),
    ]
