# Generated by Django 5.2.7 on 2026-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0002_delete_resourceconstraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Restricción"
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("CO_REQUISITE", "Co-requisito (Inclusión Obligatoria)"),
                            ("MUTUAL_EXCLUSION", "Exclusión Mutua"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Restricción",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "primary_resource_type",
                    models.CharField(
                        choices=[
                            ("runway", "Pista"),
                            ("gate", "Puerta"),
                            ("aircraft", "Aeronave"),
                            ("personnel", "Personal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Recurso Primario",
                    ),
                ),
                (
                    "primary_resource_id",
                    models.PositiveIntegerField(verbose_name="ID del Recurso Primario"),
                ),
                (
                    "related_resource_type",
                    models.CharField(
                        choices=[
                            ("runway", "Pista"),
                            ("gate", "Puerta"),
                            ("aircraft", "Aeronave"),
                            ("personnel", "Personal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Recurso Relacionado",
                    ),
                ),
                (
                    "related_resource_id",
                    models.PositiveIntegerField(
                        verbose_name="ID del Recurso Relacionado"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Restricción de Recursos",
                "verbose_name_plural": "Restricciones de Recursos",
                "ordering": ["name"],
            },
        ),
    ]
